### ISSUE TITLE
Can't Push to Heroku 

### ISSUE THREAD

**Issue by pollyking** [greyblake/blogo#14]
Hi, I can't push this app to Heroku I always get the error NameError: uninitialized constant Blogo. I tried precompiling assets but that will not run either. Everthing works perfectly in development.

**Comment by melissawahnish** [comment]
Hi!  I was able to add this app as a gem to a project and push to Heroku.  What steps did you take?

**Comment by pollyking** [comment]
Oh great. Which Rails/Ruby versions. Also, do you remember taking any unusual steps?

**Comment by greyblake** [comment]
@pollyking @melissawahnish Sorry guys for delay I am really busy now.
I'll try to take a deeper look in few days, but I haven't worked with Heroku, so I am not sure there something I can do.
@melissawahnish thanks for helping @pollyking to figure out this!

**Comment by greyblake** [comment]
Hoh) I just wonder: are you from RailsGirls?:)

**Comment by melissawahnish** [comment]
@greyblake I'm not affliated with RailsGirls, but they look like a great organization!

@pollyking I'm using Ruby 2.2 and Rails 4.2.  The only special thing was after deploying the code and running the migrations, I ran

>heroku run rake blogo:create_user[user_name,user@email.com,password]

with the user name I had chosen.

The other special thing to note is that you need to use urls to include images as Heroku doesn't permanently save images to the server.  Explained here http://stackoverflow.com/questions/24671358/heroku-doesnt-save-uploaded-images

My current plan is to upload images to Amazon S3 separately and use the url when adding an image to a blog post.

**Comment by greyblake** [comment]
Doesn't look like the issue is related to blogo gem itself, so I am cllosing this.
@melissawahnish thanks for the support!)

**Comment by melissawahnish** [comment]
No problem!

On Sat, Mar 28, 2015 at 7:53 PM, Sergey Potapov <notifications@github.com>
wrote:

> Doesn't look like the issue is related to blogo gem itself, so I am
> cllosing this.
> @melissawahnish <https://github.com/melissawahnish> thanks for the
> support!)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/greyblake/blogo/issues/14#issuecomment-87331583>.
>



-- 
Melissa Wahnish
Aarting
www.aarting.com
646-400-2777

**Comment by anandjacob15** [comment]
does anybody have server  issues after installing blogo? my server is running at 100% after installing this. just want check whether its because of blogo....

**Comment by greyblake** [comment]
@anandjacob15 I don't believe Blogo can be the reasons of such issues, unless you really have so many visitors visitors:) 
You can use `top` or `htop` tool to determine which process loads your CPU.
