### ISSUE TITLE
update sass-rails  for compatibility with Rails 4.2

### ISSUE THREAD

**Issue by bitcoder** [greyblake/blogo#16]
Rails 4.2 requires sass-rails 5.0.x but blogo requires 4.0.x.
This dependency should be updated for compatibility with Rails 4.2 :)

 bundle
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Bundler could not find compatible versions for gem "sass-rails":
  In Gemfile:
    blogo (>= 0) ruby depends on
      sass-rails (~> 4.0) ruby

    sass-rails (5.0.1)

**Comment by greyblake** [comment]
@bitcoder Thanks for reporting! I'll take care of it in few days.

**Comment by greyblake** [comment]
Fixed in https://github.com/greyblake/blogo/commit/545781a5810bd333707301d9a2b79724917ef3ed

**Comment by greyblake** [comment]
I just released version `0.1.0` with the fix.

**Comment by bitcoder** [comment]
cool
