### ISSUE TITLE
Bundler doesn't like the 0.0.10 version?

### ISSUE THREAD

**Issue by MSeneadza** [greyblake/blogo#17]
I recently updated Bundler and just did a "bundle update" and it pulled in v 0.0.1 of Blogo.  Looks like it's not differentiating between 0.0.10 and 0.0.1

I really like the gem BTW.  I'm using it here http://swingtradebot.com/blog

**Comment by greyblake** [comment]
Hi! It's a really surprising.
Can you please tell your version of `bundle -v`?

Thanks! Can I add swingtradebot to the list in README?

**Comment by greyblake** [comment]
@MSeneadza I just released version 0.1.0. Please check it out.
Thanks for using Blogo)

**Comment by MSeneadza** [comment]
I'm on Bundler version 1.8.4

Yes, You can add my site to the ReadMe... that would be great.  Thanks.

Pulling 0.1.0 now...
