### ISSUE TITLE
BCrypt gem no longer called bcrypt-ruby - update gemspec?

### ISSUE THREAD

**Issue by Zamyatin** [greyblake/blogo#18]
Hey all - 

Just started playing around with blogo gem and wanted to report a minor issue upon bundle install.  See below:

Post-install message from bcrypt-ruby:
#######################################################
The bcrypt-ruby gem has changed its name to just bcrypt.  Instead of
installing `bcrypt-ruby`, you should install `bcrypt`.  Please update your
dependencies accordingly.
#######################################################

Just wondering if this is as simple as updating gemspec?

**Comment by greyblake** [comment]
Thanks for reporting this!
FIxed in https://github.com/greyblake/blogo/commit/6f990355d84fc69e2ce6eaea41f05f981abb63e5

Yes it was simple: just to update gemspec)
