### ISSUE TITLE
Can't upload images if changing default mount link

### ISSUE THREAD

**Issue by nhuanvn** [greyblake/blogo#20]
Upload images is ok if I mounted the blog to /blog

But when I changed the route and mount the blog to /, I got an error when uploading image

Started POST "/blog/admin/images?CKEditor=post_raw_content&CKEditorFuncNum=1&langCode=en" for 127.0.0.1 at 2015-06-26 03:50:15 +0000

ActionController::RoutingError (No route matches [POST] "/blog/admin/images"):

Do we need to change any configuration to make it works

**Comment by greyblake** [comment]
Thanks for the report!
I believe not, it should work out of box. I'll try to reproduce the issue.
Can you please also provide your environment info? Rails version, ruby version?

**Comment by greyblake** [comment]
No. Just use url `/admin` instead of `/blog/admin`.

**Comment by ueharajohji** [comment]
that didn't fixed the problem.
