### ISSUE TITLE
How to edit views of blogo

### ISSUE THREAD

**Issue by stevendelarwelle** [greyblake/blogo#22]
How can i edit the veiws of blogo so they look more like my site?

**Comment by greyblake** [comment]
You have to redefine the blogo views in your application:
https://github.com/greyblake/blogo/tree/master/app/views/

Example:
To redefine layout, put the following file into you rails app `app/views/layouts/blogo/blog.html.erb` (or haml, or whatever).

Same with others. Most of the other views you are in this dir here:
https://github.com/greyblake/blogo/tree/master/app/views/blogo/posts
Likely you want to change `index` and `show` views. Of course you don't need to redefine partials, if you are not gonna use them.
