### ISSUE TITLE
unable to add new models

### ISSUE THREAD

**Issue by rajeevriitm** [greyblake/blogo#23]
I was working on this engine and I wanted to add a new model to it. But rails g model is not working . I get the following error.

` /home/raj/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rails/cli (LoadError)
	from /home/raj/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/bin/rails:9:in `<main>'

can anyone help with this.

**Comment by kont-noor** [comment]
@rajeevriitm try `rails g model` at `spec/dummy` directory

**Comment by greyblake** [comment]
Hi. There is nothing related with the blog engine itself.
Probably, you don't have rails installed.

Try to do the following:
```
bundle install
bundle rails g model <MODEL_NAME>
```
