### ISSUE TITLE
permalink and validation of blogo objects

### ISSUE THREAD

**Issue by tymat** [greyblake/blogo#26]
Blogo::Post does not validate fields particularly the permalink attribute which causes an issue when a poster puts a @ symbol or some other non-URL safe character.

**Comment by greyblake** [comment]
According to RFC document, `@` is valid URL char: http://stackoverflow.com/questions/1547899/which-characters-make-a-url-invalid

It works well if permalink contains this character.

Anyway, thanks for the report. I am gonna close the issue, please open a new one if you find something not working as it should.
