### ISSUE TITLE
Not able to create a User

### ISSUE THREAD

**Issue by linteau** [greyblake/blogo#29]
Hi I'm trying to create a user and keep getting this error message. 

command -> rake blogo:create_user [andy,andy@banzaihq.com,wowwowwow]

error -> zsh: no matches found: [andy,andy@banzaihq.com,wowwowwow]

Not sure what the problem is....

Andy

**Comment by greyblake** [comment]
You don't need to use a space betwee `_user` and `[andy`.

Try this:
```
rake blogo:create_user[andy,andy@banzaihq.com,wowwowwow]
```

**Comment by ant-camp** [comment]
@greyblake still doesnt work. Still getting the error

zsh: no matches found: blogo:create_user[admin_test,admin@test.com,testtest]

**Comment by linteau** [comment]
@ant-camp I ended up creating a user through the rails console. This worked for both local and also on heroku. 

Blogo::User.create!({:name => " First Last", :email => "guy@gmail.com", :password => "111111", :password_confirmation => "111111" })

@greyblake, I am pretty sure we are following the instructions properly. 

rake blogo:create_user[andy,andy@banzaihq.com,wowwowwow]

zsh: no matches found: blogo:create_user[andy,andy@banzaihq.com,wowwowwow]

This is still giving me the error.

**Comment by ant-camp** [comment]
@linteau thanks. got it works through the console.

**Comment by greyblake** [comment]
Hi! Sorry guys, for delay, I was on vacation.
@linteau Thanks for the work around.

As I figured out, the this is `zsh` specific problem: https://robots.thoughtbot.com/how-to-use-arguments-in-a-rake-task
You have to use escape `[` and `\]` with backslash:
```
rake blogo:create_user\[user_name,user@email.com,password\]
```

I've added this to README in "Troubleshooting" sections.

Thanks!
