### ISSUE TITLE
NoMethodError - undefined method `blogo_post_path'

### ISSUE THREAD

**Issue by rept** [greyblake/blogo#3]
I get this error when trying to go to /blog

This is the log:

  Blogo::Post Load (0.6ms)  SELECT "blogo_posts".* FROM "blogo_posts" WHERE "blogo_posts"."published" = 't' AND (published_at <= '2014-03-22 14:07:04.512054') ORDER BY published_at DESC LIMIT 10 OFFSET 0
  Blogo::Post Load (0.5ms)  SELECT "blogo_posts".* FROM "blogo_posts" WHERE "blogo_posts"."published" = 't' AND (published_at <= '2014-03-22 14:07:04.511359') ORDER BY published_at DESC LIMIT 5
  Blogo::Tag Load (0.3ms)  SELECT "blogo_tags".* FROM "blogo_tags"
  Blogo::Post Load (0.4ms)  SELECT "blogo_posts".* FROM "blogo_posts" WHERE "blogo_posts"."published" = 't' AND (published_at <= '2014-03-22 14:07:04.512054') ORDER BY published_at DESC
  Rendered /Users/stijn/.rvm/gems/ruby-2.0.0-p247/gems/blogo-0.0.7/app/views/blogo/posts/_post_header.html.erb (14097.2ms)
  Rendered /Users/stijn/.rvm/gems/ruby-2.0.0-p247/gems/blogo-0.0.7/app/views/blogo/posts/_post_overview.html.erb (16873.9ms)
  Rendered /Users/stijn/.rvm/gems/ruby-2.0.0-p247/gems/blogo-0.0.7/app/views/blogo/posts/index.html.erb within layouts/blogo/blog (20483.3ms)
Completed 500 Internal Server Error in 30318ms

NoMethodError - undefined method `blogo_post_path' for #<#<Class:0x007fc34d86c3e8>:0x007fc354db5fc8>:

It seems to happen in the _post_header:

<h1><%= link_to post.title, blogo_post_path(post) %></h1>

Any ideas?  When I do rake routes I see this:

               blogo_post GET    /blog/:permalink(.:format)                      blogo/posts#show

**Comment by hackhowtofaq** [comment]
Same problem here

Ruby 2.2.1
Rails 4.2.1

Start server and first visit to /blog 

```
undefined method `blogo_post_path' for #<#<Class:0x007f2979f79d98>:0x007f298c3e0960>

<header>
  <h1><%= link_to post.title, blogo_post_path(post) %></h1>

  <div class="posted">
    <span>
      <%= t('blogo.user.post_by') %> <%= post.user.name %>
```

Thanks in advance

**Comment by greyblake** [comment]
@hackhowtofaq thanks for the report.
It's known issue. It happens in development if you first visit any of your application's pages and then go to blog page. It doesn't happen if you visit blog page first(please correct me if it is not so).
Hopefully it doesn't happen in production.
I've spent a lot of time trying to investigate and fix this issue, but still I can't come up with any good solution or work around.

**Comment by hackhowtofaq** [comment]
> It doesn't happen if you visit blog page first(please correct me if it is not so).

It happens to me. It is the first page I visit.

I ll try in production and report back.

**Comment by hackhowtofaq** [comment]
Yeap it's working on production

**Comment by jtoy** [comment]
is this still open?

**Comment by greyblake** [comment]
@jtoy Unfortunatelly yes.

**Comment by greyblake** [comment]
Fixed with this commit: https://github.com/greyblake/blogo/commit/337a186c12653e29a2460cfac1c20d847bf85d4d

Please check out version 0.1.2

**Comment by rept** [comment]
Yay! :+1:

**Comment by jtoy** [comment]
What is the recommended way to upgrade a current blog to this?

**Comment by greyblake** [comment]
Just run `bundle update blogo`.
