### ISSUE TITLE
Text Editor not coming at heroku

### ISSUE THREAD

**Issue by shyammohankanojia** [greyblake/blogo#31]
HI 

Did any face this issue, Text Editor not coming at heroku?
Even i tried to run asset precompile at local and than push to heroku.

some one please suggest what to do in this case? see the screenshot

![screen shot 2015-12-11 at 1 41 21 am](https://cloud.githubusercontent.com/assets/148665/11727178/7633e01e-9fa8-11e5-9604-4c14f0b139cb.png)

**Comment by eterry1388** [comment]
Yes I had the same issue.  I solved it by using "non-stupid-digest-assets".  See here:  https://github.com/alexspeller/non-stupid-digest-assets

I created an initializer here:

```
config/initializers/non_digest_assets.rb
```

And added this line to it:

```
NonStupidDigestAssets.whitelist += [/ckeditor\/.*/]
```

**Comment by shyammohankanojia** [comment]
Thanks @eterry1388 

This worked for me :+1:

**Comment by MSeneadza** [comment]
Thanks @eterry1388 , I just ran into this today after changing my site's theme from Zurb to Bootstrap.  That gem did the trick!
