### ISSUE TITLE
How to create our own style ? 

### ISSUE THREAD

**Issue by Jugulaire** [greyblake/blogo#39]
I cannot personalize my blogo .. 
Could you help me?

**Comment by greyblake** [comment]
@Jugulaire What do you need exactly? 

Create a layoyut template and put it into `app/views/layouts/blogo/blog.html.erb` in your application. And you can have fun, you include any css file or whatever you want)

**Comment by Jugulaire** [comment]
I soule like to change color ans form factor of the blog. 
I juste need tout include css file in new layout ?

**Comment by greyblake** [comment]
Yes. You can also redefine any of the default templates if you want: https://github.com/greyblake/blogo/tree/master/app/views/blogo
