### ISSUE TITLE
Anyway to change template?

### ISSUE THREAD

**Issue by Yomud** [greyblake/blogo#40]
Good morning/evening. Maybe that is because I am newbie in RoR and can't see all, but how to change standard template? Looked all folders and nothing. So, IMHO, it will be great if you put this info into docs or FAQ.

**Comment by greyblake** [comment]
Hi!
Look at the source code of blogo and decide, which template you would like to change/override.
E.g. if you want to change this template: https://github.com/greyblake/blogo/blob/master/app/views/blogo/posts/show.html.erb
Create file in you application with the following path: `app/views/blogo/posts/show.html.erb` and put any content you want.
Views in your application have priority over views that come from engines, so rails will pick you template
