### ISSUE TITLE
navigation bar gone

### ISSUE THREAD

**Issue by fnumono** [greyblake/blogo#58]
So i did have my own rails app, but i want to integrate blogo into it. However, when i open localhost:3000/blog the original navigation bar is gone and I cant go back to the previous page. 

Is there a way to edit or keep my navigation bar maybe?

**Comment by greyblake** [comment]
Hey! You can overwrite default layout with your custom layout. Check details here: https://github.com/greyblake/blogo/wiki/FAQ#how-to-use-custom-layout
